# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepipe', '0003_auto_20160607_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashup',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.TextField(default='Title'),
            preserve_default=False,
        ),
    ]
