# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import imagepipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepipe', '0005_auto_20160608_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashup',
            name='image_file',
            field=models.ImageField(upload_to=imagepipe.models.unique_mashup),
        ),
        migrations.AlterField(
            model_name='source',
            name='image_file',
            field=models.ImageField(upload_to=imagepipe.models.unique_source),
        ),
    ]
